## **Project Overview**
Organizations deal with complex sales data but often lack clear insights due to:

- High sales but low profit
- Ineffective discount strategies
- Underperforming products or regions
- Limited customer insights
- Operational inefficiencies (e.g., delivery delays)

This project transforms raw data into meaningful insights to solve these challenges.

#### **Import Libraries**

In [44]:
import pandas as pd
import numpy as np
import sqlalchemy
from sqlalchemy import create_engine

#### **Data Ingestion & Loading**

*To ensure data integrity and scalability, I developed a custom Python ingestion script to migrate the raw sales dataset into a MySQL Relational Database.*

In [ ]:
engine = create_engine("mysql+pymysql://root:your_password_here@localhost:3306/sales_analysis")

try:
    tables = pd.read_sql("SHOW TABLES", engine)
    print("Connection Successful")
    print("Table(s) found in 'sales_analysis' database")
    print(tables)
except Exception as e:
    print(f"Connection Failed: {e}")
    
print("\n--- Database Overview: Preview & Counts ---")

count_df = pd.read_sql(f"SELECT COUNT(*) as total FROM {tables.iloc[0,0]}", engine)
preview_df = pd.read_sql(f"SELECT * FROM {tables.iloc[0,0]} LIMIT 5", engine)
print(f"\nTable: {tables.iloc[0,0]}")
print(f"Total Rows: {count_df['total'][0]}")
display(preview_df)

Connection Successful
Table(s) found in 'sales_analysis' database
  Tables_in_sales_analysis
0     processed_sales_data
1        superstore_orders

--- Database Overview: Preview & Counts ---

Table: processed_sales_data
Total Rows: 51289

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,profit,shipping_cost,order_priority,year,delivery_days,profit_margin,high_discount,order_year,order_month,order_month_name
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,106.140,35.46,Medium,2011,5,26.0147,0,2011,1,January
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,36.036,9.72,Medium,2011,7,30.0300,0,2011,1,January
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,29.640,8.17,High,2011,4,44.9091,0,2011,1,January
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,-26.055,4.82,High,2011,4,-57.9000,1,2011,1,January
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,37.770,4.70,Medium,2011,7,33.1316,0,2011,1,January

In [46]:
df = pd.read_sql("SELECT * FROM superstore_orders", con=engine)

#### **Data Cleaning**

##### *Summary Statistics*

In [47]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

           quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

##### *Fixing Inconsistencies*

In [48]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True)
df['ship_date'] = pd.to_datetime(df['ship_date'], dayfirst=True)

In [49]:
df[['order_date', 'ship_date']].dtypes

order_date    datetime64[ns]
ship_date     datetime64[ns]
dtype: object

In [50]:
df['sales'] = df['sales'].replace(r'[\$,]', '', regex=True)
df['sales'] = pd.to_numeric(df['sales'], errors='coerce').astype(float)

In [51]:
df['profit'] = df['profit'].replace(r'[\$,]', '', regex=True)
df['profit'] = pd.to_numeric(df['profit'], errors='coerce').astype(float)

df['shipping_cost'] = df['shipping_cost'].replace(r'[\$,]', '', regex=True)
df['shipping_cost'] = pd.to_numeric(df['shipping_cost'], errors='coerce').astype(float)

In [52]:
df[['sales', 'profit', 'shipping_cost']].dtypes

sales            float64
profit           float64
shipping_cost    float64
dtype: object

In [53]:
# Standardizing all categorical columns

text_cols = df.select_dtypes(include=['object']).columns

for col in text_cols:
    df[col] = df[col].str.strip()

- Converted date columns into proper datetime format.
- Sales column converted to float.
- Standardized text fields for consistency.

##### *Data Validation*

In [54]:
logical_errors = df[df['ship_date'] < df['order_date']]
print(f"Number of logical errors: {len(logical_errors)}")

Number of logical errors: 0

In [55]:
price_errors = df[df['sales'] <= 0]
print(f"Non-positive or zero sales found: {len(price_errors)}")

Non-positive or zero sales found: 1

In [56]:
# Keep only rows where sales are greater than 0
df = df[df['sales'] > 0]

- Checked logical errors such as shipping date cannot be greater than order date.
- Checked Price errors. Found 1 row where sales is equal to 0. Filtered out that row to maintain data consistency.

##### *Duplicates Handling*

In [57]:
# Only finds rows that are 100% identical in every single column
duplicates = df[df.duplicated()] 
print(f"Number of total identical rows: {len(duplicates)}")

Number of total identical rows: 0

- I ran a check for 100% identical rows across every single column. The result was zero. This confirms that every row in my dataset represents a unique part of a business transaction, and there is no 'garbage' or double-entry data to remove.

#### **Feature Engineering**

In [58]:
df['delivery_days'] = (df['ship_date'] - df['order_date']).dt.days

In [59]:
df['profit_margin'] = (df['profit'] / df['sales']) * 100
df['profit_margin'] = df['profit_margin'].replace([np.inf, -np.inf], 0)
df['profit_margin'] = df['profit_margin'].fillna(0)

In [60]:
df['high_discount'] = df['discount'].apply(lambda x: 1 if x > 0.2 else 0)

In [61]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_month_name'] = df['order_date'].dt.month_name()

Created new features like:
- Delivery Days (to measure shipping efficiency)
- Profit Margin (to evaluate performance)
- High Discount Flag (to analyze discount impact)

#### **Export Dataset**

In [62]:
from sqlalchemy import types

dtype_map = {
    'order_id': types.VARCHAR(50), 
    'order_date': types.DATE, 
    'ship_date': types.DATE, 
    'ship_mode': types.VARCHAR(50), 
    'customer_name': types.VARCHAR(100),
    'segment': types.VARCHAR(50), 
    'state': types.VARCHAR(100), 
    'country': types.VARCHAR(100), 
    'market': types.VARCHAR(50), 
    'region': types.VARCHAR(50), 
    'product_id': types.VARCHAR(50),
    'category': types.VARCHAR(50), 
    'sub_category': types.VARCHAR(50), 
    'product_name': types.VARCHAR(200), 
    'sales': types.FLOAT, 
    'quantity': types.INT,
    'discount': types.FLOAT, 
    'profit': types.FLOAT, 
    'shipping_cost': types.FLOAT, 
    'order_priority': types.VARCHAR(50), 
    'year': types.INT,
    'delivery_days': types.INT, 
    'profit_margin': types.FLOAT, 
    'high_discount': types.INT, 
    'order_year': types.INT,
    'order_month': types.INT, 
    'order_month_name': types.VARCHAR(50)
}

try:
    df.to_sql('processed_sales_data', con=engine, if_exists='replace', index=False, dtype=dtype_map)
    print("Success! 'processed_sales_data' table created in MySQL.")
except Exception as e:
    print(f"Error: {e}")

Success! 'processed_sales_data' table created in MySQL.